/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIReply: typeof import('./src/components/AI/AIReply.vue')['default']
    BackTop: typeof import('./src/components/BackTop.vue')['default']
    LoginForm: typeof import('./src/components/login/LoginForm.vue')['default']
    PopularDestinationsCard: typeof import('./src/components/Information/PopularDestinationsCard.vue')['default']
    RegisterForm: typeof import('./src/components/login/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowProducts: typeof import('./src/components/ShowProducts.vue')['default']
    Start: typeof import('./src/components/Assistant/Start.vue')['default']
    TabBar: typeof import('./src/components/Home/TabBar.vue')['default']
    UserQuery: typeof import('./src/components/AI/UserQuery.vue')['default']
    VanBackTop: typeof import('vant/es')['BackTop']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanLoading: typeof import('vant/es')['Loading']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
