/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    1: typeof import('./src/components/My/1.vue')['default']
    AIReply: typeof import('./src/components/AI/AIReply.vue')['default']
    BackTop: typeof import('./src/components/BackTop.vue')['default']
    Chat: typeof import('./src/components/Information/chat.vue')['default']
    Customer: typeof import('./src/components/Information/customer.vue')['default']
    MenuBar: typeof import('./src/components/My/MenuBar.vue')['default']
    MuneBar: typeof import('./src/components/My/MuneBar.vue')['default']
    PopularDestinationsCard: typeof import('./src/components/Information/PopularDestinationsCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareTourTraceCard: typeof import('./src/components/Home/ShareTourTraceCard.vue')['default']
    ShowProducts: typeof import('./src/components/ShowProducts.vue')['default']
    Start: typeof import('./src/components/Assistant/Start.vue')['default']
    TabBar: typeof import('./src/components/Home/TabBar.vue')['default']
    UserQuery: typeof import('./src/components/AI/UserQuery.vue')['default']
    VanBackTop: typeof import('vant/es')['BackTop']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    Vanimg: typeof import('vant/es')['img']
    VanImg: typeof import('vant/es')['Img']
    VanImge: typeof import('vant/es')['Imge']
    VanLoading: typeof import('vant/es')['Loading']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTa: typeof import('vant/es')['Ta']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VantImage: typeof import('vant/es')['tImage']
  }
}
